name: Saybot
description:
email: me@andrewnicolaou.co.uk
#avatar: .beepboop/inorout-icon.png
#background: .beepboop/inorout-bg.png
#screenshots:
#  - screenshot: .beepboop/screenshot1.png
#  - screenshot: .beepboop/screenshot2.png
#  - screenshot: .beepboop/inorout-long.gif
slackscopes:
  - bot
  - commands
  - reactions:write